# Hãy đổi tên file này thành "secrets.toml" và bỏ đuôi .example đi
# File này nằm trong thư mục .streamlit/ (ngang hàng với file config.toml)

GEMINI_API_KEY = "AIzaSyD1DnKFkgt3cXi7R2lCXxxAAGj2oH_I7yI"